version: "3.1"
services:
  secretary-bot:
    container_name: secretary-bot
    build: .
    restart: always
    env_file:
      - stack.env
    volumes:
      - secretary-data:/tmp
    depends_on:
      - postgres

volumes:
  secretary-data: