"""Initial revision

Revision ID: a3dcef07065b
Revises: 
Create Date: 2025-04-03 00:39:00.877748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dcef07065b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userpeermessages',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('UNKNOWN', 'ANY', 'TEXT', 'ANIMATION', 'AUDIO', 'DOCUMENT', 'PHOTO', 'STICKER', 'STORY', 'VIDEO', 'VIDEO_NOTE', 'VOICE', 'CONTACT', 'DICE', 'GAME', 'POLL', 'VENUE', 'LOCATION', 'NEW_CHAT_MEMBERS', 'LEFT_CHAT_MEMBER', 'NEW_CHAT_TITLE', 'NEW_CHAT_PHOTO', 'DELETE_CHAT_PHOTO', 'GROUP_CHAT_CREATED', 'SUPERGROUP_CHAT_CREATED', 'CHANNEL_CHAT_CREATED', 'MESSAGE_AUTO_DELETE_TIMER_CHANGED', 'MIGRATE_TO_CHAT_ID', 'MIGRATE_FROM_CHAT_ID', 'PINNED_MESSAGE', 'INVOICE', 'SUCCESSFUL_PAYMENT', 'USERS_SHARED', 'CHAT_SHARED', 'CONNECTED_WEBSITE', 'WRITE_ACCESS_ALLOWED', 'PASSPORT_DATA', 'PROXIMITY_ALERT_TRIGGERED', 'BOOST_ADDED', 'FORUM_TOPIC_CREATED', 'FORUM_TOPIC_EDITED', 'FORUM_TOPIC_CLOSED', 'FORUM_TOPIC_REOPENED', 'GENERAL_FORUM_TOPIC_HIDDEN', 'GENERAL_FORUM_TOPIC_UNHIDDEN', 'GIVEAWAY_CREATED', 'GIVEAWAY', 'GIVEAWAY_WINNERS', 'GIVEAWAY_COMPLETED', 'VIDEO_CHAT_SCHEDULED', 'VIDEO_CHAT_STARTED', 'VIDEO_CHAT_ENDED', 'VIDEO_CHAT_PARTICIPANTS_INVITED', 'WEB_APP_DATA', 'USER_SHARED', name='contenttype'), nullable=False),
    sa.Column('message', sa.JSON(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('file_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('filepath', sa.VARCHAR(length=256), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=256), nullable=True),
    sa.Column('mimetype', sa.VARCHAR(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userpeermessages')
    op.drop_table('users')
    # ### end Alembic commands ###
